name: MLOPS- CI/CD Pipeline Using GitHub Actions

# Trigger the workflow on push to main or pull requests to main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Testing model and running the pipeline
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Python environment
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run tests
        run: |
          pytest model_test.py --maxfail=1 --disable-warnings -q

      # 5. Save the trained model
      - name: Save Trained Model
        run: |
          # Train the model and save it as a .pkl file
          python -c "
          from model.model import main;
          model = main(); 
          import joblib;
          joblib.dump(model, 'iris_model.pkl')"
        if: success()

      # 6. Upload model as an artifact
      - name: Upload Model Artifact
        uses: actions/upl
